// <auto-generated />
using System;
using Absence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Absence.Infrastructure.Migrations
{
    [DbContext(typeof(AbsenceDbContext))]
    [Migration("20260406101528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Absence.Domain.Entities.Absence", b =>
                {
                    b.Property<int>("AbsenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbsenceId"));

                    b.Property<string>("AbsenceType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AbsenceId");

                    b.ToTable("Absences", (string)null);

                    b.HasDiscriminator<string>("AbsenceType").HasValue("Absence");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Absence.Domain.Entities.AnnualLeave", b =>
                {
                    b.HasBaseType("Absence.Domain.Entities.Absence");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Annual");
                });

            modelBuilder.Entity("Absence.Domain.Entities.DayOff", b =>
                {
                    b.HasBaseType("Absence.Domain.Entities.Absence");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("DayOff");
                });

            modelBuilder.Entity("Absence.Domain.Entities.SickLeave", b =>
                {
                    b.HasBaseType("Absence.Domain.Entities.Absence");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MedicalDocument")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Absences", t =>
                        {
                            t.Property("EndDate")
                                .HasColumnName("SickLeave_EndDate");

                            t.Property("StartDate")
                                .HasColumnName("SickLeave_StartDate");
                        });

                    b.HasDiscriminator().HasValue("Sick");
                });
#pragma warning restore 612, 618
        }
    }
}
